import java.io.IOException;
import java.security.NoSuchAlgorithmException;
import java.math.BigInteger;
import java.util.Scanner;
import java.security.MessageDigest;

public class Main {

    // Funkcja skrótu – funkcja przyporządkowująca dowolnie dużej liczbie krótką, zawsze posiadającą stały rozmiar, niespecyficzną, quasi-losową wartość, tzw. skrót nieodwracalny.


    public static String type;

    public static String hash_function(String input, String type)  {

        try {

            MessageDigest md = MessageDigest.getInstance(type);               // Static getInstance method is called with hashing MD5

            byte[] md_byte = md.digest(input.getBytes());                     // digest() method is called to calculate message digest of an input digest() return array of byte

            BigInteger md_bi = new BigInteger(1, md_byte);            // Convert byte array into signum representation

            String hash_text = md_bi.toString(16);                      // Convert message digest into hex value

            while (hash_text.length() < 32) {
                hash_text = "0" + hash_text;
            }

            return hash_text;
        }
        catch (NoSuchAlgorithmException e) {  throw new RuntimeException(e); }
    }

    public static void speed_and_length(String input, String type)  {

        long czasRozpoczecia = System.nanoTime();

        String out = hash_function(input, type);
        System.out.println("HashCode generated by " + type + " is: " + out);

        long czasZakonczenia = System.nanoTime();

        long czasTrwania = czasZakonczenia - czasRozpoczecia;
        System.out.println("Time: " + czasTrwania + "ns");

        System.out.println("Length: " + out.length());

        System.out.println();
    }


    public static void main(String[] args) throws IOException, NoSuchAlgorithmException {

        System.out.println("Podaj tekst wejściowy: ");

        Scanner scanner = new Scanner(System.in);
        String input = scanner.nextLine();

        type = "MD5";
        speed_and_length(input, type);

        type = "SHA-1";
        speed_and_length(input, type);

        type = "SHA-224";
        speed_and_length(input, type);

        type = "SHA-256";
        speed_and_length(input, type);

        type = "SHA-384";
        speed_and_length(input, type);

        type = "SHA-512";
        speed_and_length(input, type);

        type = "SHA3-224";
        speed_and_length(input, type);

        type = "SHA3-256";
        speed_and_length(input, type);

        type = "SHA3-384";
        speed_and_length(input, type);

        type = "SHA3-512";
        speed_and_length(input, type);



        System.out.println("Podaj tekst wejściowy nie dłuższy niż 4 znaki: ");
        String input2 = scanner.nextLine();

        type = "MD5";
        speed_and_length(input2, type);

    }
}
